services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      # Geänderter Host-Port (3002 statt 3001), um Pangolin nicht zu stören
      - "127.0.0.1:3002:3001"
    networks:
      - pangolin_frontend

networks:
  pangolin_frontend:
    external: true

